-- CREATE NEW DATABASE
CREATE DATABASE FinanceTracker;

-- CREATE TABLES
GO

USE [FinanceTracker];

CREATE TABLE TblUsers (
	[UserID] INT PRIMARY KEY IDENTITY(1,1),
	[FullName] NVARCHAR(50) NOT NULL,
	[Username] NVARCHAR(50) NOT NULL UNIQUE,
	[Password] NVARCHAR(255) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL UNIQUE,
	[CreatedDate] DATETIME DEFAULT GETDATE(),
	[ModifiedDate] DATETIME DEFAULT GETDATE()
);

CREATE TABLE TblCategory (
	[CategoryID] INT PRIMARY KEY IDENTITY(1,1),
	[CategoryName] NVARCHAR(50) NOT NULL,
	[Type] NVARCHAR(10) NOT NULL,
	[CreatedDate] DATETIME DEFAULT GETDATE(),
	[ModifiedDate] DATETIME DEFAULT GETDATE()
);

CREATE TABLE TblTransaction (
	[TransactionID] INT PRIMARY KEY IDENTITY(1,1),
	[UserID] INT NOT NULL,
	[CategoryID] INT NOT NULL,
	[Amount] DECIMAL(18, 2) NOT NULL,
	[Type] NVARCHAR(10) NOT NULL,
	[TransactionDate] DATETIME NOT NULL,
	[Description] NVARCHAR(255) NULL,
	[CreatedDate] DATETIME DEFAULT GETDATE(),
	[ModifiedDate] DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (UserID) REFERENCES TblUsers(UserID),
	FOREIGN KEY (CategoryID) REFERENCES TblCategory(CategoryID)
);

